### ISSUE TITLE
Question: possible to define multiple specs?

### ISSUE THREAD

**Issue by jacobq** [grassator/bdd-for-c#26]
It seems like this library is intended to be used in such a way that there is exactly one `spec(...)` block per executable output. That makes a lot of sense, but I would like to know: Is there any way to have it compile multiple tests in one go? (I'm guessing not since [`spec` (re)defines `__bdd_test_main__`](https://github.com/grassator/bdd-for-c/blob/master/bdd-for-c.h#L524-L526))

The reason I ask is because I am trying to use this with a [DPDK](https://www.dpdk.org/) application, and the build process is a bit [more involved](http://doc.dpdk.org/guides/prog_guide/build_app.html) than just some extra includes and libraries. I'm no `make` expert, but I haven't been able to figure out a way to build multiple tests without having a separate `Makefile` for each test :worried:. Maybe what I should do is compile the code being tested as a library then just have the tests link against it, which should simplify things quite a bit.

**Comment by grassator** [comment]
The reasoning behind doing it with only one `spec` is because C99 does not really allow a good mechanism to mechanism to declare a function and register it in some data structure at the same time.

The standard solutions for this that I don't like are:

* pre-processing file to discover all function for example starting with `spec_` or `test_` - I want bdd-for-c to be compilable with just cc so this is a no go.
* having separate `register_test` or similar function that you manually call inside your own main - this could be ok as an option but I not the default case. If you are willing to work on supporting something like `multispec(some_spec_name) {}` I'm happy to discuss more details.

Also understanding your problem better might help me to offer a good solution. If this is simply about organizing tests into multiple files, then you can always just use `#include`

**tests.c**
```c
#include "bdd-for-c.h"

spec("strncmp") {
  #include "strncmp.c"
}
```

**strncmp.c**
```c
#include <string.h>
#include "bdd-for-c.h"

describe("strncmp") {
    static const char *test_string = "foo";

    it("should return 0 when strings are equal") {
        check(strncmp(test_string, test_string, 12) == 0);
        check(strncmp(test_string, "foo", 12) == 0);
    }

    it("should work for empty strings") {
        check(strncmp("", "", 12) == 0);
    }

    it("should return non-0 when strings are not equal") {
        check(strncmp("foo", "bar", 12) != 0);
        check(strncmp("foo", "foobar", 12) != 0);
    }

    it("should return 0 when strings match up to specified length") {
        check(strncmp("foobar", "foobaz", 3) == 0);
    }
}
```

If you have problem with tests running too long one feature that can be added is support for running tests based on certain pattern, e.g. `BDD_PATTERN=str* ./test` that would be a good feature to add to the library and I would be happy to accept PRs on that.
